import { describe, expect, it } from 'vitest'
import { performCombatAttack, runEnemyTurn, type Unit, type WeaponState } from './combat'
import { applyEnemyArchetype, createWeaponState, hydrateArenaUnits, parseEquipmentCatalog } from './equipment-content'
import { createInventory } from './inventory'

const definition = { id: 'made', name: 'Made', role: 'makeshift' as const, ammoId: 'ammo', baseDamage: 10, accuracyModifier: 0, critModifier: 0, penetration: 0, magazineSize: 3, reloadAp: 3, durabilityPerShot: 2, makeshift: true }
const state = (overrides: Partial<WeaponState> = {}): WeaponState => ({ ...createWeaponState(definition, 'weapon-1'), magazine: 2, reserveAmmo: 4, durability: 20, ...overrides })
const unit = (overrides: Partial<Unit> = {}): Unit => ({ id: 'hero', name: 'Hero', team: 'player', x: 0, y: 0, hp: 30, maxHp: 30, aim: 55, color: '#fff', ap: 10, weaponState: state(), ...overrides })
const catalog = { contentVersion: 1, weapons: [definition], ammo: [{ id: 'ammo', name: 'Ammo', damageModifier: .5, penetrationModifier: .5 }], armor: [{ id: 'vest', name: 'Vest', slot: 'torso', reduction: { torso: 8 } }], enemies: [{ id: 'shooter', name: 'Shooter', behavior: 'shooter', intent: 'cover', weaponId: 'made', armorIds: ['vest'] }, { id: 'rusher', name: 'Rusher', behavior: 'rusher', intent: 'close', weaponId: 'made', armorIds: [] }, { id: 'defender', name: 'Defender', behavior: 'defender', intent: 'hold', weaponId: 'made', armorIds: ['vest'] }] }

describe('M3-A authoritative equipment combat', () => {
 it('validates catalog links and constructs enemy equipment from archetype data', () => { const parsed = parseEquipmentCatalog(catalog); const enemy = applyEnemyArchetype(unit({ id: 'enemy', team: 'enemy', archetypeId: 'shooter' }), parsed); expect(enemy).toMatchObject({ behavior: 'shooter', weaponState: { weaponId: 'made', weaponInstanceId: 'enemy-made' }, armor: { reduction: { torso: 8 }, durability: 100 } }); expect(() => parseEquipmentCatalog({ ...catalog, enemies: [{ ...catalog.enemies[0], weaponId: 'missing' }] })).toThrow('weaponId') })
 it('uses ammo modifiers and live armor in the sole shot pipeline', () => { const attacker = unit({ weaponState: state({ ammoDamageModifier: .5, ammoPenetrationModifier: .5, makeshift: false, durability: 100 }) }); const target = unit({ id: 'enemy', team: 'enemy', armor: { reduction: { torso: 8 }, durability: 100, maxDurability: 100 } }); const action = performCombatAttack(attacker, target, 'torso', 'none', { malfunction: 100, hit: 1, crit: 100 }); expect(action.resolution?.damage).toBe(11); const broken = performCombatAttack(attacker, { ...target, armor: { ...target.armor!, durability: 0 } }, 'torso', 'none', { malfunction: 100, hit: 1, crit: 100 }); expect(broken.resolution?.damage).toBe(15) })
  it('reduces and clamps the affected live armor instance durability', () => { const target = unit({ id: 'enemy', team: 'enemy', armor: { armorInstanceId: 'vest-1', armorId: 'vest', reduction: { torso: 8 }, durability: 3, maxDurability: 100 } }); const result = performCombatAttack(unit({ weaponState: state({ baseDamage: 10, makeshift: false }) }), target, 'torso', 'none', { malfunction: 100, hit: 1, crit: 100 }); expect(result.target.armor?.durability).toBe(0) })

  it('makes every enemy attack consume its archetype weapon state', () => { const enemy = applyEnemyArchetype(unit({ id: 'enemy', team: 'enemy', x: 3, archetypeId: 'rusher', weaponState: undefined }), parseEquipmentCatalog(catalog)); const result = runEnemyTurn([unit(), enemy], 5, 2, [], () => 100); expect(result.units.find(entry => entry.id === 'enemy')?.weaponState?.magazine).toBe(2) })

  it('hydrates retry equipment from persistent instances instead of static arena values', () => { const parsed = parseEquipmentCatalog(catalog); const inventory = createInventory(20, [{ instanceId: 'weapon-1', itemId: 'made', slot: 'primary', durability: 7, maxDurability: 100, magazine: 1, reserveAmmo: 9, malfunctioned: true }, { instanceId: 'vest-1', itemId: 'vest', slot: 'torso', durability: 22, maxDurability: 100 }]); const arena = { units: [unit({ weaponState: state({ durability: 100, magazine: 3, reserveAmmo: 1 }), armor: { armorInstanceId: 'vest-1', armorId: 'vest', durability: 100, maxDurability: 100, reduction: { torso: 8 } } })] }; const hydrated = hydrateArenaUnits(arena, parsed, inventory, [unit({ weaponState: state({ durability: 88, magazine: 0, reserveAmmo: 0 }) })]); expect(hydrated[0]).toMatchObject({ weaponState: { weaponInstanceId: 'weapon-1', durability: 7, magazine: 1, reserveAmmo: 9, malfunctioned: true }, armor: { armorInstanceId: 'vest-1', durability: 22 } }) })
  it('fires one injected Overwatch reaction when movement first enters LOS', () => { const hero = unit({ x: 0, y: 0, ap: 0, overwatch: { reservedAp: 4 }, weaponState: state({ magazine: 2, durability: 20, makeshift: false }) }); const enemy = unit({ id: 'enemy', team: 'enemy', x: 4, y: 1, behavior: 'rusher', weaponState: state({ weaponInstanceId: 'enemy-w', magazine: 0, reserveAmmo: 0 }) }); const rolls = [1, 100, 100]; const result = runEnemyTurn([hero, enemy], 5, 2, [{ x: 2, y: 1, kind: 'full' }], () => rolls.shift() ?? 100); expect(result.log.some((entry) => entry.startsWith('Overwatch:'))).toBe(true); expect(result.units.find((entry) => entry.id === 'hero')).toMatchObject({ hp: 30, overwatch: undefined, weaponState: { magazine: 1, durability: 18 } }); expect(result.units.find((entry) => entry.id === 'enemy')?.hp).toBeLessThan(30) })

})
