import { describe, expect, it } from 'vitest'
import { beginEnemyPhase, canBeginTransition, persistEnemyPhase, resolveEnemyPhase, resumePersistedEnemyPhase } from './session'
import { createLocalStorageAdapter, createMemoryStorage, defaultSave } from './save'
import type { ArenaConfig } from './content'
import type { Unit } from './combat'
import { startMission } from './campaign'
const hero = (overrides: Partial<Unit> = {}): Unit => ({ id: 'hero', name: 'Hero', team: 'player', x: 0, y: 0, hp: 24, maxHp: 24, aim: 55, color: '#fff', ap: 10, statuses: {}, ...overrides })
const enemy = (): Unit => ({ id: 'enemy', name: 'Enemy', team: 'enemy', x: 3, y: 0, hp: 15, maxHp: 15, aim: 55, color: '#f00', ap: 0, statuses: {} })
const arena: ArenaConfig = { contentVersion: 1, id: 'arena', name: 'Arena', width: 5, height: 2, tile: { width: 1, height: 1 }, units: [hero(), enemy()], cover: [] }
const missions = [{ id: 'encounter', zoneId: 'zone', order: 1, rewardId: 'reward', arenaId: arena.id }]
describe('campaign session transitions', () => {
 it('resolves a persisted enemy phase deterministically on reload and increments turn exactly once', () => { const base = defaultSave(arena.id, [hero(), enemy()], undefined, missions); const save = { ...base, phase: 'enemy' as const, turn: 4, activeEncounterId: base.campaign.mission.id, campaign: startMission(base.campaign, undefined, missions) }; const result = resolveEnemyPhase(save, arena); expect(result).toMatchObject({ phase: 'player', turn: 5 }); expect(resolveEnemyPhase(result, arena)).toBe(result) })
 it('creates one enemy transition only from an active mission and rejects duplicate synchronous/timer starts', () => { const save = defaultSave(arena.id, [hero(), enemy()], undefined, missions); const active = { ...save, activeEncounterId: save.campaign.mission.id, campaign: startMission(save.campaign, undefined, missions) }; const enemyPhase = beginEnemyPhase(active); expect(enemyPhase).toMatchObject({ phase: 'enemy' }); expect(enemyPhase && beginEnemyPhase(enemyPhase)).toBeNull(); expect(beginEnemyPhase(save)).toBeNull(); expect(canBeginTransition(false, 'player')).toBe(true); expect(canBeginTransition(true, 'player')).toBe(false); expect(canBeginTransition(false, 'enemy')).toBe(false) })
 it('persists enemy state before timer scheduling and boot resumes it exactly once', () => { const adapter = createLocalStorageAdapter(createMemoryStorage(), { campaignMissions: missions }); const base = defaultSave(arena.id, [hero(), enemy()], undefined, missions); const pending = persistEnemyPhase(adapter, { ...base, activeEncounterId: base.campaign.mission.id, campaign: startMission(base.campaign, undefined, missions) }); expect(pending).toMatchObject({ phase: 'enemy' }); expect(adapter.load()).toMatchObject({ ok: true, value: { phase: 'enemy' } }); const resumed = pending && resumePersistedEnemyPhase(adapter, pending, arena); expect(resumed).toMatchObject({ phase: 'player', turn: 2 }); expect(adapter.load()).toEqual({ ok: true, value: resumed }); expect(resumed && resumePersistedEnemyPhase(adapter, resumed, arena)).toBe(resumed) })
 it('reproduces enemy rolls exactly from the persisted seed after save reload', () => { const base = defaultSave(arena.id, [hero({ armor: { armorInstanceId: 'starter-vest', armorId: 'patched-vest', durability: 100, maxDurability: 100, reduction: { torso: 3 } } }), { ...enemy(), weaponState: { weaponInstanceId: 'enemy-weapon', weaponId: 'pm', name: 'PM', ammoId: '9x18', baseDamage: 20, accuracyModifier: 0, critModifier: 0, penetration: 0, ammoDamageModifier: 0, ammoPenetrationModifier: 0, magazine: 8, magazineSize: 8, reserveAmmo: 0, durability: 100, maxDurability: 100, durabilityPerShot: 1, reloadAp: 3, makeshift: false } }], undefined, missions); const save = { ...base, phase: 'enemy' as const, activeEncounterId: base.campaign.mission.id, campaign: startMission(base.campaign, undefined, missions), inventory: { ...base.inventory, equipment: [...base.inventory.equipment, { instanceId: 'enemy-weapon', itemId: 'pm', slot: 'primary' as const, durability: 100, maxDurability: 100 }] } }; const adapter = createLocalStorageAdapter(createMemoryStorage(), { campaignMissions: missions }); expect(adapter.save(save)).toBe(true); const loaded = adapter.load(); if (!loaded?.ok) throw new Error('expected save'); expect(resumePersistedEnemyPhase(adapter, loaded.value, arena)).toEqual(resolveEnemyPhase(save, arena)) })
})
